$('#DeleteTriage').click(function()
    {
        $(".hidepencil").hide();
        $(".hidedel").toggle();
    });
    $('#EditTriage').click(function()
    {
        $(".hidedel").hide();
        $(".hidepencil").toggle();
    });