    $('#DeleteLegacy').click(function()
    	    {
       $(".hidepencil").hide();
    	        $(".hidedelete").toggle();
    	    });
    	    $('#EditLegacy').click(function()
    	    {
    	        $(".hidedelete").hide();
    	        $(".hidepencil").toggle();
    	   });